Repository RegioHelden/django-datawatch, pull requests merged in 2025-04, with the labels that each got.

#66 Switch to reusable workflows and ruff linting/formatting
  MANIFEST.in
Labels: backwards-incompatible

#67 Release v7.0.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#69 Add django 5.2 support
  .devcontainer/devcontainer.json
  .github/workflows/workflow.yaml
  Dockerfile
  compose.yaml
  example/settings.py
  requirements-ci.txt
Labels: enhancement

#70 Release v7.1.0
  CHANGELOG.md
  pyproject.toml
Labels: skip-changelog

#71 Pin reusable workflow release
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
Labels: skip-changelog

#72 Move project version to standalone file
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  .github/workflows/workflow.yaml
  pyproject.toml
  version
Labels: skip-changelog

#74 Adjustments to the modulesync defaults
  .sync.yml
Labels: infrastucture

#78 Add supported python versions to sync config
  .sync.yml
Labels: infrastucture

#79 Updates from modulesync
  .github/dependabot.yml
  .github/workflows/build-and-publish.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#81 Updates from modulesync
  .devcontainer/devcontainer.json
  pyproject.toml
Labels: infrastucture

#82 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#83 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
  Dockerfile
Labels: infrastucture

#84 Updates from modulesync
  pyproject.toml
Labels: infrastucture

#85 Updates from modulesync
  .github/workflows/build-and-publish.yaml
  .github/workflows/check_pull_request.yaml
  .github/workflows/cron.yaml
  .github/workflows/open-release-pr.yaml
  .github/workflows/tag-release.yaml
Labels: infrastucture

#86 Updates from modulesync
  Dockerfile
Labels: infrastucture
